"""add image to post

Revision ID: 38c3f44ebaab
Revises: 5f0c38243373
Create Date: 2025-05-29 07:52:18.453453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38c3f44ebaab'
down_revision = '5f0c38243373'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instrument_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instrument_post', schema=None) as batch_op:
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###
