"""add price field to instrument post

Revision ID: 849a7e79f05f
Revises: 6fdc6a6cf8c0
Create Date: 2025-06-05 02:55:01.529109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '849a7e79f05f'
down_revision = '6fdc6a6cf8c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instrument_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instrument_post', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
