"""Add views column to InstrumentPost

Revision ID: e7cce676c1c7
Revises: 849a7e79f05f
Create Date: 2025-06-05 04:29:44.600532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7cce676c1c7'
down_revision = '849a7e79f05f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instrument_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('views', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instrument_post', schema=None) as batch_op:
        batch_op.drop_column('views')

    # ### end Alembic commands ###
