"""empty message

Revision ID: ea239b077032
Revises: e7cce676c1c7
Create Date: 2025-06-05 04:46:55.560750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea239b077032'
down_revision = 'e7cce676c1c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instrument_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instrument_post', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
